spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 10
      min-idle:  0
      max-active: 10
server:
  port: 8080
