spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 10
      min-idle:  0
      max-active: 10
server:
  port: 8010
logging:
  level: info
